### PR TITLE
Adds tests, and updates README to reflect running tests

### LINKED ISSUE #1: Tests
Need to add tests for all functions.

### PR DESCRIPTION
**Pull request by taveras**
This (mostly?) closes #1

While the tests may not be super valuable, it atleast ensures you can refactor without breaking the current module interface.
I opted to use `mocha` and `chai`.

Hope this follows your code style for this package, @maxmechanic !

### CODE REVIEW

**Comment by maxmechanic** [comment]
Thanks so much for this PR @taveras! This is awesome.

Those testing/coverage tools are ones I use and like, so that's great. 

Going to think for a moment on this to see if there's a reasonable way to DRY up the test code, but that's unlikely to hold this up too much.

I'll also make sure to add an `.eslintrc`, and to get this wired up with Travis for CI once this is in.

**Comment by taveras** [comment]
@maxmechanic I pushed a commit to make the tests more DRY. I don't always particularly love making tests DRY, as too much 'magic' can make tests harder to read.

If we don't plan on having special test cases for certain test suites, this should be fine. any thoughts?

**Comment by maxmechanic** [comment]
I completely understand and sympathize with your aversion to magical test helpers. For me it's weighing some abstraction against the repetitiveness of testing a library like this, and I get why it should be used _and_ why it should be avoided.

That said, I really appreciate the time you spent coming up with a solution. Splitting a little bit of the difference, do you think it's worth having an array of functions on the prototype to test vs the more general `Object.keys`? I don't imagine there will be other static values, but it perhaps restores a bit more explicitness. 

I'm happy either way, and I'll get this into `master` (hopefully soon followed by a release!) when I hear from you.

**Comment by taveras** [comment]
Ah, certainly! I agree that this feels to be a good scenario to keep the tests DRY.

Having the list of methods to test as an array sounds fair.
Do you mean creating a constant within the test file such as: 
```javascript
var METHOD_LIST = ['update', 'get', 'etc'];
```
Or instead creating a property on the module, such as:
```javascript
Pinboard.protoype.methodNames = ['update', 'get', 'etc'];
``` 

Both options make testing feel more explicit, but I would probably lean towards the former.
No worries from me either way, I'm excited for the new release! 😄

**Comment by maxmechanic** [comment]
A constant in the test file was what I was thinking of, so that works out!

**Comment by maxmechanic** [comment]
Going to refactor against this test suite among other things, so I'll handle that method list. Thanks again for this PR!

**Pull request merged**
